In [ ]:
import numpy as np

In [ ]:
vector = np.array([1, 2, 3, 4, 5])

In [ ]:
mean = np.mean(vector)

In [ ]:
variance = np.var(vector)


In [ ]:
print("Mean:", mean)
print("Variance:", variance)

Mean: 3.0
Variance: 2.0


In [ ]:
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

In [ ]:
covariance = np.cov(vector1, vector2, bias=True)[0][1]

In [ ]:
print("Covariance:", covariance)

Covariance: 0.6666666666666666


In [ ]:
vector3 = np.array([1, 2, 3])
vector4 = np.array([4, 5, 6])

In [ ]:
correlation = np.corrcoef(vector1, vector2)[0][1]


In [ ]:
print("Correlation:", correlation)

Correlation: 1.0


In [ ]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [ ]:
cov_matrix = np.cov(matrix, bias=True)

In [ ]:
corr_matrix = np.corrcoef(matrix)

In [ ]:
print("Covariance Matrix:\n", cov_matrix)
print("Correlation Matrix:\n", corr_matrix)

Covariance Matrix:
 [[0.66666667 0.66666667 0.66666667]
 [0.66666667 0.66666667 0.66666667]
 [0.66666667 0.66666667 0.66666667]]
Correlation Matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
